[package]
name = "aemilius-agent-rust" # Le nom interne de votre crate Rust
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"           # Le nom du module binaire compilé (.so / .pyd)
crate-type = ["cdylib"]   # Indique à Rust de compiler une bibliothèque dynamique pour Python
path = "src/rust/lib.rs"     # Force Cargo à chercher votre code dans votre dossier "rust"

[dependencies]
# PyO3 fournit les liaisons entre Rust et Python
# "extension-module" est obligatoire pour créer un module Python chargeable
pyo3 = { version = "0.23", features = ["extension-module"] }